#!/usr/bin/env node

const { readFileSync, existsSync, writeFileSync } = require('fs');
const path = require('path');

const { promisify } = require('util');
const _exec = promisify(require('child_process').exec);
const moment = require('moment');
const { prompt } = require('inquirer');
const GitHub = require('github');
const ProgressBar = require('progress');

const DRY_RUN = !!process.env.DRY_RUN;

DRY_RUN && console.log('❗️  DRY RUN ❗️');
function exec(cmd) {
  if (DRY_RUN) {
    return new Promise(resolve => setTimeout(resolve, 1));
  }
  return _exec(`${cmd}`);
}

function getMomentForPosition(x, y, refDate) {
  return moment(refDate)
    .add(x, 'weeks')
    .add(y, 'days')
    .hour(12);
}

async function recreateRepo({ GITHUB_API_TOKEN, GITHUB_REPO, GITHUB_USER }) {
  // removing the repo removes the dots from the graph
  const github = new GitHub();
  github.authenticate({
    type: 'token',
    token: GITHUB_API_TOKEN,
  });
  try {
    !DRY_RUN &&
      (await github.repos.delete({
        owner: GITHUB_USER,
        repo: GITHUB_REPO,
      }));
  } catch (err) {
    // prob 404
  }
  console.log(`✅  Deleted repo ${GITHUB_USER}:${GITHUB_REPO}`);
  !DRY_RUN &&
    (await github.repos.create({
      name: GITHUB_REPO,
      description: '🐱 Generated by gitkatt',
      homepage: 'https://github.com/KATT/gitkatt',
    }));
  console.log(`✅  Created repo ${GITHUB_USER}:${GITHUB_REPO}..`);
}

function paintingToCoords(art, refDate) {
  const painting = [];
  let x = 0,
    y = 0;
  for (const char of art) {
    if (char === '\n') {
      y++;
      x = 0;
      continue;
    }
    if (y > 6) {
      throw new Error('Too many lines in art (max 7 rows).');
    }

    const date = getMomentForPosition(x, y, refDate);

    painting.push({ date, char });

    x++;
  }

  return painting;
}

async function main() {
  if (!existsSync('./art')) {
    const contents = readFileSync(path.join(__dirname, 'art'));
    writeFileSync('./art', contents);
    const info = [
      'ℹ️  Notied that you didn\'t an "art" file. So we created an example for you.',
      'ℹ️  Have a look and edit it to your liking.',
    ];
    console.log(info.join('\n'));
  }
  const questions = [
    {
      type: 'input',
      name: 'GITHUB_USER',
      message: 'GitHub username',
      default: process.env.GITHUB_USER,
      validate: val => !!val,
    },
    {
      type: 'input',
      name: 'GITHUB_API_TOKEN',
      message: 'GitHub API Token',
      default: process.env.GITHUB_API_TOKEN,
      validate: val => val.length > 10 || 'Enter a valid API TOKEN',
    },
    {
      type: 'input',
      name: 'ART_FILENAME',
      message: 'Filename for art',
      default: process.env.ART_FILENAME || 'art',
      validate: val => existsSync(`./${val}`) || 'Enter an existing file',
    },
    {
      type: 'input',
      name: 'GITHUB_REPO',
      message: 'Repository name',
      default: process.env.GITHUB_REPO || 'gitkatt-child-repo',
      validate: val => !!val,
    },
    {
      type: 'input',
      name: 'DRAW_START_DATE',
      message: 'Start date for drawing',
      default: process.env.DRAW_START_DATE || '2017-03-05',
      validate: val => moment(val).isoWeekday() === 7 || 'Needs to be a Sunday',
    },
    {
      type: 'input',
      name: 'NUM_LAYERS',
      message: 'Number of layers to draw',
      default: process.env.NUM_LAYERS || 50,
      filter: val => parseInt(val),
      validate: val => (val > 0 && val < 100) || 'Needs to be 1-100',
    },
  ];

  const {
    GITHUB_USER,
    GITHUB_API_TOKEN,
    GITHUB_REPO,
    DRAW_START_DATE,
    ART_FILENAME,
    NUM_LAYERS,
  } = await prompt(questions);

  const ART = readFileSync(`./${ART_FILENAME}`).toString();

  console.log(ART);

  const painting = paintingToCoords(ART, DRAW_START_DATE);

  const cmds = painting.reduce((res, { date, char }) => {
    if (char !== ' ') {
      const content = `${date.format('YYYY-MM-DD')} ${Math.random()}`;
      const cmd = `echo '${
        content
      }' >> meow && git add meow && git commit --date='${date.toJSON()}' -m '🐱'`;

      return [...res, cmd];
    }
    return res;
  }, []);

  const bar = new ProgressBar('Creating initial layer', {
    complete: '=',
    incomplete: ' ',
    width: 20,
    total: NUM_LAYERS * cmds.length,
  });

  await recreateRepo({ GITHUB_API_TOKEN, GITHUB_USER, GITHUB_REPO });

  // recreate repo a few times to have more history (makes it darker)
  for (let i = 0; i < NUM_LAYERS; i++) {
    if (i === 1) {
      const url = `https://github.com/${GITHUB_USER}`;
      process.stderr.cursorTo(0);
      process.stderr.clearLine(1);
      process.stderr.write(`✅  Now viewable on your GitHub - ${url}\n`);
    }
    let state =
      i > 0 ? `Darkening (${i}/${NUM_LAYERS})` : 'Creating initial layer';
    bar.fmt = `🚧  ${state} [:bar] :percent :etas`;

    await exec(
      `rm -rf ./generated-repo && mkdir ./generated-repo && cd ./generated-repo && git init`,
    );

    for (const cmd of cmds) {
      bar.tick();
      await exec(`cd ./generated-repo && ${cmd}`);
    }

    await exec(
      `cd ./generated-repo && git remote add origin git@github.com:${
        GITHUB_USER
      }/${GITHUB_REPO}.git && git push origin master --force`,
    );
  }
}

main()
  .then(() => {
    console.log('😻  - it should be all set and done! ');
  })
  .catch(err => {
    console.error('🙀', err);
  });
